### ISSUE TITLE
exceptions reporting

### ISSUE THREAD

**Issue by oleksmarkh** [obviel/obviel#7]
The most common exception I have during regular templating is `Uncaught TypeError: Cannot read property 'nodeType' of undefined`. It's not explicit and forces to debug obviel itself to see what typo did I make.

Please consider the following case (reversed):
1. I have that exception thrown from `module.getXpath()` in `obviel-template.js` because `el` is `undefined` but not `null` and `el.nodeType` fails.
2. That `el` param comes from `obviel.template.getXpath(e.el)` call of `exceptionInfo()`.
3. `e` there refers to any kind of exception thrown during compilation, not necessarily related to a malformed template - it could be a silly JS mistake in `before()` method of a view.

What I'm trying to say that it's not visible from a first glance what actually went wrong and developer has to fight the laziness and dig into obviel to catch an original exception.

I'm not sure what's a proper way to improve exceptions handling/reporting - just relaxing that `while (el !== null && el.nodeType === 1)` check or inserting some `console.error()` calls.

**Comment by allblackt** [comment]
I totally agree with OP. I've encountered this error numerous times and solved it just by reading my code carefully and trying to understand what went wrong.
